version: '3'

networks:
  mysql-compose-network:
    driver: bridge
  monitor-net:
    driver: bridge


services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "apibr@2021#"
      MYSQL_DATABASE: "ApiBR"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    image: adminer
    ports:
      - 8084:8080
    networks:
      - mysql-compose-network

  apibr:
    container_name: apibr
    depends_on:
      - mysqlsrv
    build:
      context: ../apibr-application
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - monitor-net
      - mysql-compose-network
