version: '3'

networks:
  mysql-compose-network:
    driver: bridge
  monitoring:
    driver: bridge


services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "apibr@2021#"
      MYSQL_DATABASE: "ApiBR"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - mysql-compose-network
      - monitoring
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    image: adminer
    ports:
      - 8084:8080
    networks:
      - mysql-compose-network

  apibr:
    container_name: apibr
    depends_on:
      - mysqlsrv
    build:
      context: ../apibr-application
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - monitoring
      - mysql-compose-network

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ../prometheus/config:/etc/prometheus/
      - ../prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ../grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    networks:
      - monitoring
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
